dist: trusty
language: node_js
node_js:
  - "6"
  - "8"
  - "10"
before_script:
  - npm audit --audit-level high
script:
   - npm run lint
   - npm run test
branches:
  only:
    - master
    - /^greenkeeper/.*$/